import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Add next-themes ThemeProvider
import { ThemeProvider } from "@/components/ThemeProvider";
import ThemeToggle from "@/components/ThemeTogggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ristar Logistics",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black dark:bg-black`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {/* Theme toggle button in top-right */}
          <div style={{ position: "fixed", top: 16, right: 32, zIndex: 999999 }} className="pointer-events-auto">
            <ThemeToggle />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
